from . import sale_order_line
from . import product_template
from . import approval_product_line
from . import mrp_workcenter_capacity
from . import mrp_bom_line
from . import mrp_bom_byproduct
from . import stock_move
from . import purchase_order_line
from . import account_move_line
from . import stock_move_line
